import type { Metadata } from 'next';
import { Footer, Navbar } from '@/components/shared';
import { QueryProvider } from '@/lib/react-query/Provider';
import { Toaster } from 'sonner';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='relative min-h-screen'>
        <QueryProvider>
            <Toaster
              richColors
              className='font-rubikMedium text-base max-sm:text-sm'
            />
            <Navbar />
            <main className='h-full min-h-[calc(100vh-144px)]'>{children}</main>
            <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
